// Statistics page functionality
document.addEventListener('DOMContentLoaded', function() {
    loadStatistics();
    setupEventListeners();
});

function loadStatistics() {
    // Load current data from localStorage - using the correct key from the main counter
    const saved = localStorage.getItem('antiochSundayService');
    let koreanCount = 0;
    let foreignerCount = 0;
    let koreanClicksToday = 0;
    let foreignerClicksToday = 0;
    let totalKoreanClicks = 0;
    let totalForeignerClicks = 0;
    
    if (saved) {
        try {
            const data = JSON.parse(saved);
            koreanCount = data.koreanCount || 0;
            foreignerCount = data.foreignerCount || 0;
            koreanClicksToday = data.koreanClicksToday || 0;
            foreignerClicksToday = data.foreignerClicksToday || 0;
            totalKoreanClicks = data.totalKoreanClicks || 0;
            totalForeignerClicks = data.totalForeignerClicks || 0;
        } catch (error) {
            console.error('Error loading saved data:', error);
        }
    }
    
    // Calculate totals
    const totalToday = koreanClicksToday + foreignerClicksToday;
    const thisSunday = koreanCount + foreignerCount;
    
    // Update display
    document.getElementById('koreanToday').textContent = koreanClicksToday;
    document.getElementById('foreignerToday').textContent = foreignerClicksToday;
    document.getElementById('totalToday').textContent = totalToday;
    document.getElementById('thisSunday').textContent = thisSunday;
}

function setupEventListeners() {
    // Export stats button
    document.getElementById('exportStatsBtn').addEventListener('click', exportStats);
    
    // Share stats button
    document.getElementById('shareStatsBtn').addEventListener('click', shareStats);
    
    // View history button
    document.getElementById('viewHistoryBtn').addEventListener('click', toggleHistory);
    
    // Reset Sunday button
    document.getElementById('resetSundayBtn').addEventListener('click', resetSunday);
}

function exportStats() {
    // Load data from the correct localStorage key
    const saved = localStorage.getItem('antiochSundayService');
    let koreanCount = 0;
    let foreignerCount = 0;
    let koreanClicksToday = 0;
    let foreignerClicksToday = 0;
    let totalKoreanClicks = 0;
    let totalForeignerClicks = 0;
    
    if (saved) {
        try {
            const data = JSON.parse(saved);
            koreanCount = data.koreanCount || 0;
            foreignerCount = data.foreignerCount || 0;
            koreanClicksToday = data.koreanClicksToday || 0;
            foreignerClicksToday = data.foreignerClicksToday || 0;
            totalKoreanClicks = data.totalKoreanClicks || 0;
            totalForeignerClicks = data.totalForeignerClicks || 0;
        } catch (error) {
            console.error('Error loading saved data:', error);
        }
    }
    
    const totalToday = koreanClicksToday + foreignerClicksToday;
    const thisSunday = koreanCount + foreignerCount;
    const currentDate = new Date().toLocaleDateString();
    
    const statsText = `Sunday Service Statistics - ${currentDate}

Korean Attendees: ${koreanCount}
Foreigner Attendees: ${foreignerCount}
Total This Sunday: ${thisSunday}

Today's Statistics:
Korean Today: ${koreanClicksToday}
Foreigner Today: ${foreignerClicksToday}
Total Today: ${totalToday}

All Time Totals:
Total Korean Clicks: ${totalKoreanClicks}
Total Foreigner Clicks: ${totalForeignerClicks}
Grand Total: ${totalKoreanClicks + totalForeignerClicks}

Generated by Antioch International Ministry
SOOYOUNGRO CHURCH`;

    // Create and download file
    const blob = new Blob([statsText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `sunday-stats-${currentDate.replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    // Haptic feedback
    if (navigator.vibrate) {
        navigator.vibrate(100);
    }
}

function shareStats() {
    // Load data from the correct localStorage key
    const saved = localStorage.getItem('antiochSundayService');
    let koreanCount = 0;
    let foreignerCount = 0;
    let koreanClicksToday = 0;
    let foreignerClicksToday = 0;
    let totalKoreanClicks = 0;
    let totalForeignerClicks = 0;
    
    if (saved) {
        try {
            const data = JSON.parse(saved);
            koreanCount = data.koreanCount || 0;
            foreignerCount = data.foreignerCount || 0;
            koreanClicksToday = data.koreanClicksToday || 0;
            foreignerClicksToday = data.foreignerClicksToday || 0;
            totalKoreanClicks = data.totalKoreanClicks || 0;
            totalForeignerClicks = data.totalForeignerClicks || 0;
        } catch (error) {
            console.error('Error loading saved data:', error);
        }
    }
    
    const totalToday = koreanClicksToday + foreignerClicksToday;
    const thisSunday = koreanCount + foreignerCount;
    const currentDate = new Date().toLocaleDateString();
    
    const shareText = `Sunday Service Statistics - ${currentDate}

This Sunday:
Korean: ${koreanCount}
Foreigner: ${foreignerCount}
Total: ${thisSunday}

Today's Statistics:
Korean Today: ${koreanClicksToday}
Foreigner Today: ${foreignerClicksToday}
Total Today: ${totalToday}

All Time Totals:
Total Korean: ${totalKoreanClicks}
Total Foreigner: ${totalForeignerClicks}
Grand Total: ${totalKoreanClicks + totalForeignerClicks}

Antioch International Ministry`;

    // Try native sharing first
    if (navigator.share) {
        navigator.share({
            title: 'Sunday Service Statistics',
            text: shareText,
            url: window.location.href
        }).catch(err => {
            console.log('Share failed:', err);
            fallbackShare(shareText);
        });
    } else {
        fallbackShare(shareText);
    }
    
    // Haptic feedback
    if (navigator.vibrate) {
        navigator.vibrate(100);
    }
}

function fallbackShare(shareText) {
    // Create share modal
    const modal = document.createElement('div');
    modal.style.cssText = `
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0,0,0,0.8);
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 1000;
    `;
    
    const modalContent = document.createElement('div');
    modalContent.style.cssText = `
        background: white;
        padding: 30px;
        border-radius: 12px;
        max-width: 90%;
        max-height: 80%;
        overflow-y: auto;
    `;
    
    modalContent.innerHTML = `
        <h3>📧 Share Statistics</h3>
        <p>Copy the statistics below:</p>
        <textarea style="width: 100%; height: 150px; margin: 15px 0; padding: 10px; border: 1px solid #ddd; border-radius: 5px;">${shareText}</textarea>
        <div style="display: flex; gap: 10px; justify-content: center;">
            <button onclick="navigator.clipboard.writeText('${shareText.replace(/'/g, "\\'")}').then(() => alert('Copied to clipboard!')).catch(err => console.log('Copy failed:', err))" style="background: #28a745; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">Copy</button>
            <button onclick="window.open('mailto:?subject=Sunday Service Statistics&body=${encodeURIComponent(shareText)}')" style="background: #007bff; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">Email</button>
            <button onclick="window.open('https://wa.me/?text=${encodeURIComponent(shareText)}')" style="background: #25d366; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">WhatsApp</button>
            <button onclick="this.parentElement.parentElement.parentElement.remove()" style="background: #6c757d; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer;">Close</button>
        </div>
    `;
    
    modal.appendChild(modalContent);
    document.body.appendChild(modal);
}

function toggleHistory() {
    const historySection = document.getElementById('historySection');
    const historyList = document.getElementById('historyList');
    
    if (historySection.style.display === 'none') {
        // Show history
        historySection.style.display = 'block';
        loadHistory();
    } else {
        // Hide history
        historySection.style.display = 'none';
    }
    
    // Haptic feedback
    if (navigator.vibrate) {
        navigator.vibrate(100);
    }
}

function loadHistory() {
    const historyList = document.getElementById('historyList');
    
    // Load attendance history from the correct localStorage key
    const saved = localStorage.getItem('antiochSundayService');
    let attendanceHistory = [];
    
    if (saved) {
        try {
            const data = JSON.parse(saved);
            attendanceHistory = data.attendanceHistory || [];
        } catch (error) {
            console.error('Error loading attendance history:', error);
        }
    }
    
    if (attendanceHistory.length === 0) {
        historyList.innerHTML = '<p style="text-align: center; color: #666; padding: 20px;">No attendance history available.</p>';
        return;
    }
    
    let historyHTML = '';
    attendanceHistory.slice(-10).reverse().forEach(entry => {
        historyHTML += `
            <div class="history-item">
                <div class="history-date">${entry.date} ${entry.time}</div>
                <div class="history-stats">
                    <span>Type: ${entry.type}</span>
                    <span>Korean: ${entry.koreanCount}</span>
                    <span>Foreigner: ${entry.foreignerCount}</span>
                    <span>Total: ${entry.total}</span>
                </div>
            </div>
        `;
    });
    
    historyList.innerHTML = historyHTML;
}

function resetSunday() {
    if (confirm('Are you sure you want to reset all counters for this Sunday? This action cannot be undone.')) {
        // Load current data to preserve all-time totals
        const saved = localStorage.getItem('antiochSundayService');
        let data = {
            koreanCount: 0,
            foreignerCount: 0,
            koreanHistory: [],
            foreignerHistory: [],
            totalKoreanClicks: 0,
            totalForeignerClicks: 0,
            koreanClicksToday: 0,
            foreignerClicksToday: 0,
            lastClickDate: null,
            attendanceHistory: []
        };
        
        if (saved) {
            try {
                const existingData = JSON.parse(saved);
                // Preserve all-time totals but reset current Sunday counts
                data = {
                    ...existingData,
                    koreanCount: 0,
                    foreignerCount: 0,
                    koreanHistory: [],
                    foreignerHistory: [],
                    koreanClicksToday: 0,
                    foreignerClicksToday: 0,
                    lastClickDate: null
                };
            } catch (error) {
                console.error('Error loading existing data:', error);
            }
        }
        
        // Save the reset data
        localStorage.setItem('antiochSundayService', JSON.stringify(data));
        
        // Reload statistics
        loadStatistics();
        
        // Haptic feedback
        if (navigator.vibrate) {
            navigator.vibrate(200);
        }
        
        alert('All counters have been reset for this Sunday.');
    }
}

function goBack() {
    // Navigate back to the main counter page
    window.location.href = 'index-v2.html';
} 